name 'jenkins-agent'
maintainer 'Abhishek Ranjan'
maintainer_email 'abhisran60@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures Jenkins SSH agent (worker node)'
version '0.1.0'
chef_version '>= 16.0'
