source 'https://supermarket.chef.io'

metadata

# Local dependencies
cookbook 'apt', path: '../../system/apt'
cookbook 'package', path: '../../system/package'
cookbook 'nagios-client', path: '../../nagios/nagios-client'
cookbook 'prometheus-client', path: '../../prometheus/prometheus-client'
