name 'prometheus-server'
maintainer 'Abhishek Ranjan'
maintainer_email 'abhisran6@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures Prometheus monitoring server'
version '0.1.0'
chef_version '>= 16'
