name 'jenkins-server'
maintainer 'Abhishek Ranjan'
maintainer_email 'abhisran60@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures Jenkins server (controller)'
version '0.1.2'
chef_version '>= 16.0'
