name 'jenkins-server'
maintainer 'Abhishek Ranjan'
maintainer_email 'abhisran6@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures Jenkins server (controller)'
version '0.2.8'
chef_version '>= 16.0'

depends 'chef-vault', '~> 4.0'
depends 'firewall'
depends 'apt'
depends 'package'
depends 'nagios-client'
depends 'prometheus-client'
depends 'nfs-client'
