name 'prometheus-client'
maintainer 'Abhishek Ranjan'
maintainer_email 'abhisran6@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures Prometheus Node Exporter for system metrics collection'
version '0.1.1'
chef_version '>= 16'

depends 'chef-vault', '~> 4.0'
depends 'firewall'
