source 'https://supermarket.chef.io'

metadata

cookbook 'firewall', path: '../../system/firewall'
cookbook 'apt', path: '../../system/apt'
cookbook 'package', path: '../../system/package'
cookbook 'prometheus-client', path: '../../prometheus/prometheus-client'
