name 'nagios-client'
maintainer 'Abhishek Ranjan'
version '0.1.2'
chef_version '>= 16'
description 'Installs and configures NRPE client for Nagios monitoring'

depends 'firewall'
depends 'apt'
depends 'package'
depends 'prometheus-client'
