name 'firewall'
maintainer 'Abhishek Ranjan'
maintainer_email 'abhisran6@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures UFW firewall with role-based port rules'
version '0.1.3'
chef_version '>= 16.0'
